import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from 'pdf-lib';
import type { DiagnosisResult } from '@/lib/types/diagnosis';
import { buildReportAnalysis } from '@/lib/pdf/report-analysis';
import {
  collectBlockIds,
  collectReportTexts,
  drawJpLines,
  drawJpText,
  embedJapaneseBlockFonts,
  wrapJpLines,
} from '@/lib/pdf/jp-font-blocks';

/** A4 landscape */
const PAGE_WIDTH = 841.89;
const PAGE_HEIGHT = 595.28;
const MARGIN = 50;
const HEADER_H = 72;
const CONTENT_W = PAGE_WIDTH - MARGIN * 2;
const CONTENT_TOP = PAGE_HEIGHT - HEADER_H - 28;

interface ReportFonts {
  latin: PDFFont;
  jp: Map<number, PDFFont>;
}

async function loadReportFonts(pdfDoc: PDFDocument, data: DiagnosisResult): Promise<ReportFonts> {
  const blockIds = collectBlockIds(...collectReportTexts(data));
  const [latin, jp] = await Promise.all([
    pdfDoc.embedFont(StandardFonts.Helvetica),
    embedJapaneseBlockFonts(pdfDoc, blockIds),
  ]);
  return { latin, jp };
}

const NAVY = rgb(0.051, 0.106, 0.243);
const ACCENT = rgb(0.106, 0.337, 0.69);
const MUTED = rgb(0.533, 0.6, 0.733);
const WHITE = rgb(1, 1, 1);
const CARD = rgb(0.086, 0.125, 0.251);

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleString('ja-JP', { timeZone: 'Asia/Tokyo' });
  } catch {
    return iso;
  }
}

function fillPageBg(page: PDFPage): void {
  const { width, height } = page.getSize();
  page.drawRectangle({ x: 0, y: 0, width, height, color: NAVY });
}

function drawHeader(page: PDFPage, fonts: ReportFonts): void {
  const { width, height } = page.getSize();
  page.drawRectangle({ x: 0, y: height - HEADER_H, width, height: HEADER_H, color: NAVY });
  page.drawText('GEO Search Protocol TM', {
    x: MARGIN,
    y: height - 44,
    size: 10,
    font: fonts.latin,
    color: WHITE,
  });
  page.drawText('AI Visibility Report', {
    x: MARGIN,
    y: height - 58,
    size: 8,
    font: fonts.latin,
    color: ACCENT,
  });
}

function addLandscapePage(pdfDoc: PDFDocument): PDFPage {
  return pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
}

function drawAnalysisBlock(
  page: PDFPage,
  fonts: ReportFonts,
  x: number,
  y: number,
  maxWidth: number,
  title: string,
  block: { score: number; label: string; text: string },
): number {
  drawJpText(
    page,
    `${title} — ${block.score}点 (${block.label})`,
    x,
    y,
    11,
    fonts.jp,
    WHITE,
  );
  return drawJpLines(
    page,
    wrapJpLines(block.text, 10, maxWidth, fonts.jp),
    x,
    y - 18,
    10,
    fonts.jp,
    MUTED,
  );
}

export async function generateReportPdf(data: DiagnosisResult): Promise<Buffer> {
  const pdfDoc = await PDFDocument.create();
  const fonts = await loadReportFonts(pdfDoc, data);
  const analysis = buildReportAnalysis(data);
  const s = data.scores;

  const p1 = addLandscapePage(pdfDoc);
  fillPageBg(p1);
  drawHeader(p1, fonts);

  p1.drawText('AI Visibility Report', {
    x: MARGIN,
    y: CONTENT_TOP,
    size: 24,
    font: fonts.latin,
    color: WHITE,
  });
  p1.drawText('Generated by GEO Search Protocol TM', {
    x: MARGIN,
    y: CONTENT_TOP - 28,
    size: 11,
    font: fonts.latin,
    color: MUTED,
  });

  const infoY = CONTENT_TOP - 72;
  p1.drawRectangle({ x: MARGIN, y: infoY, width: CONTENT_W, height: 64, color: CARD });
  drawJpText(p1, '店舗情報', MARGIN + 12, infoY + 48, 9, fonts.jp, MUTED);
  drawJpText(p1, data.shopName, MARGIN + 12, infoY + 28, 14, fonts.jp, WHITE);
  drawJpText(p1, `${data.area} · ${data.industry}`, MARGIN + 12, infoY + 10, 10, fonts.jp, MUTED);
  drawJpText(
    p1,
    `診断日時: ${formatDate(data.analyzedAt)}`,
    MARGIN + CONTENT_W * 0.55,
    infoY + 28,
    9,
    fonts.jp,
    MUTED,
  );

  const boxY = infoY - 88;
  const boxW = (CONTENT_W - 12) / 2;
  p1.drawRectangle({ x: MARGIN, y: boxY, width: boxW, height: 64, color: ACCENT });
  p1.drawText('Local GEO Score', {
    x: MARGIN + 12,
    y: boxY + 42,
    size: 8,
    font: fonts.latin,
    color: WHITE,
  });
  p1.drawText(String(s.localGeoScore), {
    x: MARGIN + 12,
    y: boxY + 14,
    size: 22,
    font: fonts.latin,
    color: WHITE,
  });

  p1.drawRectangle({ x: MARGIN + boxW + 12, y: boxY, width: boxW, height: 64, color: CARD });
  p1.drawText('AI Visibility Score', {
    x: MARGIN + boxW + 24,
    y: boxY + 42,
    size: 8,
    font: fonts.latin,
    color: MUTED,
  });
  p1.drawText(String(s.aiVisibilityScore), {
    x: MARGIN + boxW + 24,
    y: boxY + 14,
    size: 22,
    font: fonts.latin,
    color: WHITE,
  });

  drawJpText(p1, '総評', MARGIN, boxY - 28, 14, fonts.jp, WHITE);
  drawJpLines(
    p1,
    wrapJpLines(analysis.overall, 10, CONTENT_W, fonts.jp),
    MARGIN,
    boxY - 50,
    10,
    fonts.jp,
    MUTED,
  );

  const p2 = addLandscapePage(pdfDoc);
  fillPageBg(p2);
  drawHeader(p2, fonts);

  const colW = (CONTENT_W - 16) / 2;
  const leftX = MARGIN;
  const rightX = MARGIN + colW + 16;
  let leftY = CONTENT_TOP;
  let rightY = CONTENT_TOP;

  drawJpText(p2, '詳細分析', MARGIN, CONTENT_TOP + 4, 14, fonts.jp, WHITE);
  leftY = CONTENT_TOP - 24;
  rightY = CONTENT_TOP - 24;

  const page2Rows: [string, { score: number; label: string; text: string }][] = [
    ['FAQ分析', analysis.page2.faq],
    ['GoogleMap最適化', analysis.page2.googleMap],
    ['AI引用分析', analysis.page2.aiCitation],
    ['口コミ分析', analysis.page2.reviews],
  ];
  for (const [title, block] of page2Rows) {
    const targetX = leftY >= rightY ? leftX : rightX;
    const nextY = (targetX === leftX ? leftY : rightY) - 8;
    const endY = drawAnalysisBlock(p2, fonts, targetX, nextY, colW, title, block);
    if (targetX === leftX) leftY = endY - 12;
    else rightY = endY - 12;
  }

  const p3 = addLandscapePage(pdfDoc);
  fillPageBg(p3);
  drawHeader(p3, fonts);

  drawJpText(p3, '競合比較 · 改善提案', MARGIN, CONTENT_TOP + 4, 14, fonts.jp, WHITE);

  let leftColY = CONTENT_TOP - 24;
  const p3LeftBlocks: [string, string][] = [
    [`ChatGPT表示分析 (${analysis.page3.chatgpt.score}点)`, analysis.page3.chatgpt.text],
    [`Gemini表示分析 (${analysis.page3.gemini.score}点)`, analysis.page3.gemini.text],
    ['競合比較', analysis.page3.competitor.text],
  ];
  for (const [title, text] of p3LeftBlocks) {
    drawJpText(p3, title, leftX, leftColY, 11, fonts.jp, WHITE);
    leftColY = drawJpLines(
      p3,
      wrapJpLines(text, 10, colW, fonts.jp),
      leftX,
      leftColY - 18,
      10,
      fonts.jp,
      MUTED,
    );
    leftColY -= 12;
  }

  let rightColY = CONTENT_TOP - 24;
  drawJpText(p3, '改善ポイント', rightX, rightColY, 13, fonts.jp, WHITE);
  rightColY -= 20;
  analysis.page3.improvements.forEach((item, i) => {
    rightColY = drawJpLines(
      p3,
      wrapJpLines(`${i + 1}. ${item}`, 10, colW, fonts.jp),
      rightX,
      rightColY,
      10,
      fonts.jp,
      MUTED,
      14,
    );
    rightColY -= 4;
  });

  rightColY -= 8;
  drawJpText(p3, 'Local GEO TM 改善提案', rightX, rightColY, 13, fonts.jp, WHITE);
  rightColY -= 20;
  drawJpLines(
    p3,
    wrapJpLines(analysis.page3.localGeoProposal, 10, colW, fonts.jp),
    rightX,
    rightColY,
    10,
    fonts.jp,
    MUTED,
  );

  p3.drawText('© CoaRetail G.K. · GEO Search Protocol TM for Local', {
    x: MARGIN,
    y: 32,
    size: 8,
    font: fonts.latin,
    color: MUTED,
  });

  return Buffer.from(await pdfDoc.save({ useObjectStreams: true }));
}
